[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
exclude = '''
/(
    \.idea
  | \.vscode
  | \.git
  | \.venv.*
  | venv.*
  | __pycache__
)/
'''

[tool.isort]
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true
force_grid_wrap = 0
default_section = 'THIRDPARTY'
known_first_party = ['aiosdcp']
combine_as_imports = true
